services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      CLIENT_ID: your_client_id
      CLIENT_SECRET: your_client_secret
      PGDATABASE: followchecker
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: followchecker-db-1
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: followchecker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: